name: First long name

on:
  push:

env:
  REPO_NAME: 'cerberus'
  REPO_DIR: '$REPO_NAME/packages/cam-app'
  NAME: 'image-organizer'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'FIRST WORKFLOW'
      - run: echo ${{ env.REPO_DIR}}
      - name: Checkout cam-app-release-automation
        uses: actions/checkout@v2
        with:
          repository: egll-tech/${{ env.NAME }}
