# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run unit tests

on:
  push:
    branches: [master, release*, beta-*, FRON-*, feature-*]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [FRON-*, feature-*]

jobs:
  # checkout:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [12.x]

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         always-auth: true
  #         node-version: ${{ matrix.node-version }}
  #         registry-url: https://registry.npmjs.org
  #         scope: '@nzxt'
  #     - run: npm ci
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  #     - id: npm-cache
  #       run: |
  #         echo "::set-output name=dir::$(npm config get cache)"
  #     - uses: actions/cache@v2
  #       with:
  #         path: ${{ steps.npm-cache.outputs.dir }}
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-node-
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 1
        uses: actions/github-actions@v1
        with:
          auth-token: ${{secrets.NPM_TOKEN}}
      - name: Running tests
        run: npm run jest
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 1
        uses: actions/github-actions@v1
        with:
          auth-token: ${{secrets.NPM_TOKEN}}
      - name: Running lint
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 1
        uses: actions/github-actions@v1
        with:
          auth-token: ${{secrets.NPM_TOKEN}}
      - name: Building
        run: npm run build
  trigger_event:
    needs: [tests, lint, build]
    runs-on: ubuntu-latest
    env:
      TESTS_RESULT: ${{ needs.tests.result }}
      LINT_RESULT: ${{ needs.lint.result }}
      BUILD_RESULT: ${{ needs.build.result }}
    steps:
      - run: echo {{ needs.tests.result }} {{ needs.lint.result }} {{ needs.build.result }} $TESTS_RESULT $LINT_RESULT $BUILD_RESULT ${{ needs.tests.result }} ${{ needs.lint.result }} ${{ needs.build.result }}
