name: schedule test
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to be published'
        required: false

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo something
          echo ${{ github.event.inputs.branch }}