name: Testing changing environment variables

on:
  push:

env:
  VARIABLE: 'initial text'
  # RENDER_VARIABLE4: (jq -r .version package.json)
  RENDER_VARIABLE2: jq -r .version package.json
  # RENDER_VARIABLE4: grep -o '"version": *"[^"]*' package.json | grep -o '[^"]*$'
  # RENDER_VARIABLE4: grep -o '"version": *"[^"]*' package.json | grep -o '[^"]*$'
  BRANCH: echo $GITHUB_REF | sed -e 's/refs*\///g' -e 's/heads*\///g' -e 's/tags*\///g'
  REPO_DIR: asd

jobs:
  first-job:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          echo ${{ env.VARIABLE }}
          echo "VARIABLE2=new" >> $GITHUB_ENV
          echo $VARIABLE2
          echo $VARIABLE3
          echo "testing variables"
          echo $( ${{ env.RENDER_VARIABLE2 }} )
          echo $( $RENDER_VARIABLE2 )
          echo "RENDER_VARIABLE2=$( ${{ env.RENDER_VARIABLE2 }} )" >> $GITHUB_ENV
          echo "BRANCH=$( ${{ env.BRANCH }} )" >> $GITHUB_ENV
          echo $BRANCH
          echo ${{ env.BRANCH }}
          echo ${{ github.ref }}
          
          echo "======================================================="
          echo ${{ hashFiles('./package.json') }}
          echo ${{ hashFiles('**/package.json') }}    
          echo ${{ hashFiles('./**/package.json') }}


          # mkdir ${{ env.REPO_DIR }}
          # cp package.json ${{ env.REPO_DIR }}/
          ls -l ${{ env.REPO_DIR }}
          # cd ${{ env.REPO_DIR }}
          # npm version minor
          # cd ..
          echo ${{ hashFiles('./package.json') }}
          echo ${{ hashFiles('**/package.json') }}
          echo ${{ hashFiles('./**/package.json') }}
          echo ${{ hashFiles('./${ env.REPO_DIR }/package.json')}}
          echo ${{ hashFiles('./${ $REPO_DIR }/package.json')}}
          echo ${{ hashFiles('./${ {{ env.REPO_DIR }} }/package.json')}}
          echo ${{ hashFiles('./${ ${{ env.REPO_DIR }} }/package.json')}}
          echo ${{ hashFiles('./*/package.json') }}
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: eagle-${{ env.RENDER_VARIABLE2 }}-${{ (env.RENDER_VARIABLE2) }}-${{ env.BRANCH}}-$BRANCH
          path: LICENSE
  second-job:
    if: ${{ contains( github.ref, 'master') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  third-job:
    if: ${{ contains( github.ref, 'master') || github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  fourth-job:
    if: ${{ contains( github.ref, 'master') && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  five-job:
    if: ${{ contains( github.ref, 'master1') || github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  sixth-job:
    if: ${{ contains( github.ref, 'master1') && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  seventh-job:
    if: ${{ contains( github.ref, 'master') || github.ref == 'refs/heads/master1' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  eigth-job:
    if: ${{ contains( github.ref, 'master') && github.ref == 'refs/heads/master1' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  third-job-2:
    if: ${{ contains( github.ref, 'master') }} || ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  fourth-job-2:
    if: ${{ contains( github.ref, 'master') }} && ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  five-job-2:
    if: ${{ contains( github.ref, 'master1') }} || ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  sixth-job-2:
    if: ${{ contains( github.ref, 'master1') }} && ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  seventh-job-2:
    if: ${{ contains( github.ref, 'master') }} || ${{ github.ref == 'refs/heads/master1' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  eigth-job-2:
    if: ${{ contains( github.ref, 'master') }} && ${{ github.ref == 'refs/heads/master1' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  first-job-3:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          echo ${{ env.VARIABLE }}
          echo "VARIABLE2=new" >> $GITHUB_ENV
          echo $VARIABLE2
          echo $VARIABLE3
          echo "testing variables"
          echo $( ${{ env.RENDER_VARIABLE2 }} )
          echo $( $RENDER_VARIABLE2 )
          echo "RENDER_VARIABLE2=$( ${{ env.RENDER_VARIABLE2 }} )" >> $GITHUB_ENV
          echo "BRANCH=$( ${{ env.BRANCH }} )" >> $GITHUB_ENV
          echo $BRANCH
          echo ${{ env.BRANCH }}
          echo ${{ github.ref }}
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: eagle-${{ env.RENDER_VARIABLE2 }}-${{ (env.RENDER_VARIABLE2) }}-${{ env.BRANCH}}-$BRANCH
          path: LICENSE
  second-job-3:
    if: contains( github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  third-job-3:
    if: contains( github.ref, 'master') || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  fourth-job-3:
    if: contains( github.ref, 'master') && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  five-job-3:
    if: contains( github.ref, 'master1') || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  sixth-job-3:
    if: contains( github.ref, 'master1') && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  seventh-job-3:
    if: contains( github.ref, 'master') || github.ref == 'refs/heads/master1'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3
  eigth-job-3:
    if: contains( github.ref, 'master') && github.ref == 'refs/heads/master1'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $VARIABLE2
          echo ${{ env.VARIABLE }}
          echo $VARIABLE3